baseurl = "https://pipetbooks.org/"
relativeurls = true
languageCode = "en-us"
title = "pipetbooks"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "render_post"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[[menu.logo]]
    name = "Bookdown"
    pre = "https://github.com/pipetcpt/introduction/raw/master/assets/PIPET-A-02.JPG"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Books"
    url = "/archive/"
    weight = 4
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5
[[menu.main]]
    name = "Authors"
    url = "/authors/"
    weight = 6

[[menu.icons]]
    name = "Github"
    post = "github"
    url = "https://github.com/pipetcpt/pipetbooks.com"
    weight = 1
[[menu.icons]]
    name = "Twitter"
    post = "twitter"
    url = "https://twitter.com/shanmdphd"
    weight = 2
[[menu.icons]]
    name = "RSS"
    post = "rss"
    url = "/index.xml"
    weight = 3

[params]
    description = "Pharmacometrics books published by PIPET"
    footer = "&copy; [PIPET](https://www.pipet.or.kr) 2014 -- 2020"
